spring.application.name=ServiceRequest

spring.profiles.active=dev

server.servlet.context-path=/api

security.jwt.access-token-expiration=${JWT_TOKEN_EXPIRATION:3600}
security.jwt.issuer=${JWT_ISSUER:localhost}

# To make testing easy these keys are already created
# In a production enviroment it need to create it's own
security.jwt.public-key=classpath:keys/public.pem
security.jwt.private-key=classpath:keys/private.pem