CREATE TABLE states (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(2) NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT uk_states_code UNIQUE (code)
);

CREATE TABLE analyst_coverage (
    user_id UUID NOT NULL PRIMARY KEY,

    CONSTRAINT fk_analyst_coverage_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE analyst_coverage_states (
    user_id UUID NOT NULL,
    state_id INTEGER NOT NULL,

    PRIMARY KEY (user_id, state_id),

    CONSTRAINT fk_analyst_coverage_states_coverage
        FOREIGN KEY (user_id)
        REFERENCES analyst_coverage (user_id),

    CONSTRAINT fk_analyst_coverage_states_state
        FOREIGN KEY (state_id)
        REFERENCES states (id)
);

INSERT INTO states (code, name) VALUES
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapa'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceara'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espirito Santo'),
    ('GO', 'Goias'),
    ('MA', 'Maranhao'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Para'),
    ('PB', 'Paraiba'),
    ('PR', 'Parana'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piaui'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondonia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'Sao Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins');
